name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  validate-go-releaser:
    name: Validate GoReleaser configuration
    runs-on: ubuntu-latest
    steps:
      - name: "[Setup] repository"
        uses: actions/checkout@v4
      - name: "[CI] GoReleaser"
        uses: goreleaser/goreleaser-action@v6
        with:
          args: check
  validate-title:
    name: Validate title
    runs-on: ubuntu-latest
    steps:
      - name: "[CI] PR Title"
        uses: lab42/ccu-action@v0.1.7
        with:
          pr_title: ${{ github.event.pull_request.title }}
  validate-dockerfile:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: "[Setup] repository"
        uses: actions/checkout@v4
      - name: "[CI] Validate Dockerfile"
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: tty
          failure-threshold: error
