name: Tag
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
  id-token: write
  packages: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "[Setup] repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "[Setup] Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: "[Setup] qemu"
        uses: docker/setup-qemu-action@v3
      - name: "[Setup] buildx"
        uses: docker/setup-buildx-action@v3
      - name: "[Setup] ghcr login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: "[Setup] Syft"
        uses: anchore/sbom-action/download-syft@v0.18.0
      - name: "[Setup] Cosign"
        uses: sigstore/cosign-installer@v3.8.0
      - name: "[Setup] Cosign key"
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: echo "${COSIGN_PRIVATE_KEY}" > cosign.key
      - name: "[CD] GoReleaser"
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
